{{- $cfg := .Values.brc721 -}}
{{- if $cfg.serviceAccount.create | default true }}
{{- $saName := default (printf "%s-sa" .Release.Name) $cfg.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  labels:
    app: {{ .Release.Name }}
{{- with $cfg.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
