apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  labels:
    app: bitcoind
  {{- with .Values.bitcoind.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.bitcoind.service.type }}
  {{- if and (eq .Values.bitcoind.service.type "LoadBalancer") .Values.bitcoind.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.bitcoind.service.loadBalancerIP }}
  {{- end }}
  {{- if eq .Values.bitcoind.service.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.bitcoind.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: rpc
      port: {{ .Values.bitcoind.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
    - name: p2p
      port: {{ .Values.bitcoind.service.p2pPort }}
      targetPort: p2p
      protocol: TCP
  selector:
    app: bitcoind
---
apiVersion: v1
kind: Service
metadata:
  name: bitcoind-headless
  labels:
    app: bitcoind
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: rpc
      port: {{ .Values.bitcoind.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
    - name: p2p
      port: {{ .Values.bitcoind.service.p2pPort }}
      targetPort: p2p
      protocol: TCP
  selector:
    app: bitcoind
