chain: regtest
storageClassName: standard

bitcoind:
  image:
    repository: lncm/bitcoind
    tag: v28.0
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    rpcPort: 18443
    p2pPort: 18444
    annotations: {}
    loadBalancerIP: ""
    externalTrafficPolicy: Cluster

  rpc:
    user: dev
    password: dev
    rpcauth: ""
    bind: 0.0.0.0
    allowIPs:
      - 0.0.0.0/0

  storage:
    size: 100Gi
    accessModes:
      - ReadWriteOnce
    dataDir: /data/bitcoin

  podAnnotations: {}
  podLabels: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraArgs: []
